base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.14"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.14"
  tools:
    name: "4.14"
    namespace: ocp
    tag: tools
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.14"
  target:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: aro-f7
  cron: 36 23 6,13,20,27 * *
  steps:
    cluster_profile: azure-qe
    env:
      ARO_CLUSTER_VERSION: 4.14.16
    test:
    - ref: openshift-extended-upgrade-pre
    - ref: cucushift-upgrade-prepare
    - ref: cucushift-upgrade-prehealthcheck
    - ref: cucushift-ota-preupgrade
    - ref: cucushift-upgrade-toimage
    - ref: cucushift-upgrade-rhel-worker
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-aro
zz_generated_metadata:
  branch: release-4.14
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-4.14-upgrade-from-aro-4.14
