base_images:
  cli:
    name: "4.17"
    namespace: ocp
    tag: cli
  cluster-api-actuator-pkg-test:
    name: cluster-api-actuator-pkg-test
    namespace: ci
    tag: "4.15"
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.15"
  tools:
    name: "4.15"
    namespace: ocp
    tag: tools
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.15"
  target:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: aro-hcp-f14
  cron: 13 21 9,23 * *
  steps:
    cluster_profile: azure-qe
    env:
      ARO_CLUSTER_FILES: api.login api.url cluster-id cluster-name cluster-type console.url
        kubeconfig kubeadmin-password
    test:
    - ref: openshift-e2e-test-clusterinfra-qe
    workflow: cucushift-installer-rehearse-azure-aro-existing
zz_generated_metadata:
  branch: release-arohcp-existing-cluster
  org: openshift
  repo: openshift-tests-private
