base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.14"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.14"
  tools:
    name: "4.14"
    namespace: ocp
    tag: tools
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.14"
  target:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: aro-f30
  cron: 28 7 4 * *
  steps:
    cluster_profile: azure-qe
    env:
      ARO_CLUSTER_VERSION: 4.14.16
      TEST_SKIPS: deploymentconfigs\| should expose cluster services outside the cluster\|
        FIPS TestFIPS\| Multi-stage image builds should succeed\| Optimized image
        builds should succeed\| build can reference a cluster service\| custom build
        with buildah\| oc new-app should succeed\| prune builds based on settings\|
        s2i build with a root\| verify /run filesystem contents\| oc can run\| oc
        debug\| oc idle\| Pods cannot access\| Image append should create\| Image
        extract should extract\| Image info should display\| Image layer subresource\|
        oc tag should change image\| when installed on the cluster should\| OpenShift
        alerting rules\| The HAProxy router should\| egressrouter cni resources\|
        pod should start\| pod sysctls\| build volumes should mount given secrets
        and configmaps into the build pod
    test:
    - ref: openshift-e2e-test
    workflow: cucushift-installer-rehearse-azure-aro
zz_generated_metadata:
  branch: release-4.14
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly-4.14-upgrade-from-aro-4.14e2e
